# Generated by Django 5.2.14 on 2026-05-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkinDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('common_name', models.CharField(help_text='e.g., Melanoma', max_length=100)),
                ('description', models.TextField()),
                ('cause', models.TextField()),
                ('medicine', models.TextField()),
                ('cure_method', models.TextField()),
            ],
        ),
    ]
